# Site settings
title: "My Resume"
description: "Advertising myself to the world!"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "false"
resume_name:                    "Mahi Kiran Siddareddy"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "mahikiranreddy.adm@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "925-366-0642"
resume_contact_address:         "Austin, Texas"

resume_header_contact_info:     "Austin, Texas • 925-366-0642 • mahikiranreddy.adm@gmail.com"
display_header_contact_info:    "true"

resume_header_intro: "<p>Experienced cloud/devops engineer with background in systems and network engineering. Well-versed in AWS cloud platform and infrastructre as code tools like Terraform and Cloudformation. Innovative thinker and passionate about building new tools to drive efficiency and solve complex problems for the Organization.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
# resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/mahisid"
  # resume_twitter_url:           "http://twitter.com/jglovier"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/mahisiddareddy"
  # resume_instagram_url:         "insert your Instagram URL here"
  # resume_website_url:           "http://joelglovier.com"
  # resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
